### ISSUE TITLE
Authorization Code grant get accessken token error

### ISSUE THREAD

**Issue by godfrey-yin** [oauthjs/node-oauth2-server#315] opened 2016-06-23 15:44 UTC
Authorization Code grant get access token not return expires.
in this code not provide accessken token expires.
AuthorizationCodeGrantType.prototype.saveToken = function(user, client, authorizationCode, scope) {
  const fns = [
    this.generateAccessToken(),
    this.generateRefreshToken()
  ];

  return Promise.all(fns)
    .bind(this)
    .spread(function(accessToken, refreshToken) {
      var token = {
        accessToken: accessToken,
        authorizationCode: authorizationCode,
        refreshToken: refreshToken,
        scope: scope
      };

```
  return this.model.saveToken(token, client, user);
});
```

};

**Comment by maxtruxa** [comment] 2016-06-23 16:27
This is a duplicate of #304.

**Comment by mjsalinger** [comment] 2016-11-09 11:17
Closing as dup.

**Closed by mjsalinger** 2016-11-09 11:17 UTC
