### ISSUE TITLE
Examples 

### ISSUE THREAD

**Issue by davamale** [oauthjs/node-oauth2-server#311] opened 2016-06-17 15:48 UTC
There seems to be an issue with the examples. I can't find any.

**Comment by maxtruxa** [comment] 2016-06-17 19:24
Duplicate of #287. There are currently no examples for v3.

If you need examples for the version currently published on npm ([`oauth2-server@2.4.1`](https://www.npmjs.com/package/oauth2-server)) see this commit hash: [b36a06b445ad0a676e6175d68a8bd0b2f3353dbf](https://github.com/oauthjs/node-oauth2-server/commit/b36a06b445ad0a676e6175d68a8bd0b2f3353dbf).

**Closed** 2016-06-17 19:36 UTC
